CONSUMER_KEY1="IYq1Ax7qwENmDG1saQfgOoS3X"
CONSUMER_SECRET1="0KDk0ZZ76FOEXwcoIJ1PJ6A8iK148Ri0ITqOFsOFEnWTfKoLM1"
ACCESS_TOKEN_KEY1="3370410904-bYQfF8e2G3z1SDdSpC7QFPpYw0H0tGTCkT2m2lE"
ACCESS_TOKEN_SECRET1="e6VI7K0xCFlHLvFPOIzIn5nwccVV8KNqBFCA7VrPYZHMJ"
#And some other stuff

CONSUMER_KEY2="Ec15ENXzOo1YqOJiNLIt6qYdb"
CONSUMER_SECRET2="ZcqTHZS6wd4mxTPQ26k34SqcUOasoLYKDhXqe2plEnLa46zkov"
ACCESS_TOKEN_KEY2="3370410904-DaJHoH2Nz4hbacQERfqFYNStFJqPawN7eqonTaa"
ACCESS_TOKEN_SECRET2="BAiQcx7ly8WM5zDWD7rkoiIwvswn2nM7neiClRVudC8IH"
#And some other stuff




dic1 = {"CONSUMER_KEY":"IYq1Ax7qwENmDG1saQfgOoS3X", "CONSUMER_SECRET":"0KDk0ZZ76FOEXwcoIJ1PJ6A8iK148Ri0ITqOFsOFEnWTfKoLM1", "ACCESS_TOKEN_KEY":"3370410904-bYQfF8e2G3z1SDdSpC7QFPpYw0H0tGTCkT2m2lE","ACCESS_TOKEN_SECRET": "e6VI7K0xCFlHLvFPOIzIn5nwccVV8KNqBFCA7VrPYZHMJ"}
dic2 = {"CONSUMER_KEY": "Ec15ENXzOo1YqOJiNLIt6qYdb", "CONSUMER_SECRET":"ZcqTHZS6wd4mxTPQ26k34SqcUOasoLYKDhXqe2plEnLa46zkov", "ACCESS_TOKEN_KEY": "3370410904-DaJHoH2Nz4hbacQERfqFYNStFJqPawN7eqonTaa", "ACCESS_TOKEN_SECRET":"BAiQcx7ly8WM5zDWD7rkoiIwvswn2nM7neiClRVudC8IH"}
